Centralize releasability checks
knative/release pull request #192
Opened 2023-04-04 15:49 UTC by dprotaso

Going to do a follow up on the documentation in another PR

2023-04-04 15:49 UTC, dprotaso commented
/assign @kvmware

2023-04-04 16:33 UTC, kvmware commented
I do not like the multiple files for each repo. This would be much less overhead to have all the logic in one file that runs through a matrix of repos (external file that one can add/remove from). That would eliminate the multitude of files and the boiler plate script.

2023-04-04 16:35 UTC, kvmware requested changes
I can look into the badges of docs but I don't know if having badges on the docs site is worth this.

2023-04-04 16:35 UTC, kvmware commented on .github/workflows/releasability.yaml
> +      repo:
The repos here should just be read in from the `repos.yaml` file and matrix across this workflow.

2023-04-04 16:36 UTC, dprotaso commented
Badge are only at the workflow level

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

2023-04-04 16:37 UTC, dprotaso commented
Also the badges aren't on the docs site but the documentation here - https://github.com/knative/release/blob/main/TIMELINE.md

2023-04-05 13:59 UTC, kvmware commented
I created an issue here https://github.com/knative/release/issues/193 that outlines the concerns here that can be taken care of at another time. For now the good done with this change out weighs the concerns.

2023-04-05 14:00 UTC, merged